start = 'Wellcome to PewdsBot, {}! Here you wil be notificated about the latest videos of PewDiePie :3'
help_ = '/help - list of all commands\n/new - latest video\n/videos - last 10 videos'
user_info = 'Name: {0}\nLast name: {1}\nUsername: @{2}\nId: {3}\n\n'
videos = '{0}) {1}\n{2}\n'
new_video = 'LATEST VIDEO:\n\n{0}\n\n{1}'
