start = 'Wellcome to PewdsBot, {}! Here you wil be notificated about the latest videos of PewDiePie :3'
help_ = '/help - list of all commands\n/new - latest video\n/videos - last 10 videos'
user_info = 'Your name: {0}\nYour last name: {1}\nYour username: @{2}\nYour id: {3}'
videos = '{0}) {1}\n{2}\n'
new_video = 'LATEST VIDEO:\n\n{0}\n\n{1}'
